[versions]
kotlin = "2.3.20-Beta1"
ktor = "3.4.1"
koin = "4.2.0-RC2"
koin-compiler = "0.4.0"
logback = "1.5.32"
exposed = "0.61.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
koin-compiler = { id = "io.insert-koin.compiler.plugin", version.ref = "koin-compiler" }

[libraries]
ktor-bom = { module = "io.ktor:ktor-bom", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation" }
ktor-server-call-logging = { module = "io.ktor:ktor-server-call-logging" }
ktor-server-status-pages = { module = "io.ktor:ktor-server-status-pages" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth" }
ktor-server-auth-jwt = { module = "io.ktor:ktor-server-auth-jwt" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin" }
koin-ktor = { module = "io.insert-koin:koin-ktor" }
koin-annotations = { module = "io.insert-koin:koin-annotations" }
koin-logger-slf4j = { module = "io.insert-koin:koin-logger-slf4j" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
